apiVersion: v1
kind: Service
metadata:
  name: test-psql
  namespace: n8n
spec:
  selector:
    app: test-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-psql
  namespace: n8n
  labels:
    app: test-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-postgres
  template:
    metadata:
      labels:
        app: test-postgres
    spec:
      containers:
      - name: postgres
        image: repo.payrad.org/postgres:15
        env:
        - name: POSTGRES_PASSWORD
          value: "XC8buGC3NYjTgnMvMkRahQag2iHFSK7eW"
        - name: POSTGRES_USER
          value: "n8n"
        - name: POSTGRES_DB
          value: "n8n"
        - name: HOST
          value: "172.21.86.223"
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"